apiVersion: v1
kind: Template
metadata:
  name: hawtio-online
parameters:
- name: ROUTE_HOSTNAME
  description: The externally-reachable host name that routes to the Hawtio Online service
- name: OPENSHIFT_MASTER
  description: The OpenShift master URL used to obtain OAuth access tokens
  required: true
message: |-
  Hawtio Online is deployed to ${ROUTE_HOSTNAME}.
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: hawtio-online
    labels:
      app: hawtio
      component: online
  spec:
    tags:
    - from:
        kind: DockerImage
        name: docker.io/hawtio/integration:latest
      importPolicy:
        scheduled: true
      name: latest
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: hawtio
      component: online
    name: hawtio-online
  spec:
    replicas: 1
    selector:
      app: hawtio
      component: online
      deploymentconfig: hawtio-online
    strategy:
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app: hawtio
          component: online
          deploymentconfig: hawtio-online
      spec:
        containers:
        - image: 'hawtio/integration'
          imagePullPolicy: Always
          name: hawtio-online
          ports:
          - containerPort: 8080
          env:
          - name: OPENSHIFT_MASTER
            value: ${OPENSHIFT_MASTER}
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - hawtio-online
        from:
          kind: ImageStreamTag
          name: hawtio-online:latest
      type: ImageChange
    - type: ConfigChange
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: hawtio
      component: online
    name: hawtio-online
  spec:
    ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
    selector:
      app: hawtio
      component: online
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: hawtio
      component: online
    name: hawtio-online
  spec:
    host: ${ROUTE_HOSTNAME}
    to:
      kind: Service
      name: hawtio-online
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: hawtio-oauth-client
    labels:
      app: hawtio-online
    annotations:
      serviceaccounts.openshift.io/oauth-redirecturi.dev: http://localhost:2772
      serviceaccounts.openshift.io/oauth-redirecturi.nginx: http://localhost:8080
      serviceaccounts.openshift.io/oauth-redirecturi.route: https://
      serviceaccounts.openshift.io/oauth-redirectreference.route: '{"kind": "OAuthRedirectReference", "apiVersion": "v1", "reference": {"kind": "Route","name": "hawtio-online"}}'