apiVersion: v1
kind: Template
metadata:
  name: hawtio-online
parameters:
- name: ROUTE_HOSTNAME
  description: The externally-reachable host name that routes to the Hawtio Online service
  required: true
- name: OPENSHIFT_MASTER
  description: The OpenShift master URL used to obtain OAuth access tokens
  required: true
message: |-
  Hawtio Online is deployed to ${ROUTE_HOSTNAME}.
objects:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: hawtio-online
  data:
    hawtconfig.json: |
      {
        "branding": {
          "appName": "Hawtio OpenShift Console",
          "logoUrl": "img/hawtio-logo.svg"
        }
      }
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: hawtio-integration
  data:
    hawtconfig.json: |
      {
        "branding": {
          "appName": "Hawtio Integration Console",
          "logoUrl": "img/hawtio-logo.svg"
        }
      }
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: hawtio-online
    labels:
      app: hawtio
      component: online
  spec:
    tags:
    - from:
        kind: DockerImage
        name: docker.io/hawtio/online:latest
      importPolicy:
        scheduled: true
      name: latest
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: hawtio-integration
    labels:
      app: hawtio
      component: integration
  spec:
    tags:
    - from:
        kind: DockerImage
        name: docker.io/hawtio/integration:latest
      importPolicy:
        scheduled: true
      name: latest
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: hawtio
      component: online
    name: hawtio-online
  spec:
    replicas: 1
    selector:
      app: hawtio
      component: online
      deploymentconfig: hawtio-online
    strategy:
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app: hawtio
          component: online
          deploymentconfig: hawtio-online
      spec:
        containers:
        - image: 'hawtio/online'
          imagePullPolicy: Always
          name: hawtio-online
          ports:
          - name: nginx
            containerPort: 9090
          livenessProbe:
            httpGet:
              path: /online
              port: nginx
            periodSeconds: 10
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /online
              port: nginx
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 1
          env:
          - name: OPENSHIFT_MASTER
            value: ${OPENSHIFT_MASTER}
          - name: HAWTIO_ONLINE_MODE
            value: cluster
          volumeMounts:
          - name: hawtio-online
            mountPath: /usr/share/nginx/html/hawtconfig.json
            subPath: hawtconfig.json
        - image: 'hawtio/integration'
          imagePullPolicy: Always
          name: hawtio-integration
          ports:
          - name: integration
            containerPort: 8080
          livenessProbe:
            httpGet:
              path: /integration
              port: integration
            periodSeconds: 10
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /integration
              port: integration
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 1
          volumeMounts:
          - name: hawtio-integration
            mountPath: /usr/share/nginx/html/hawtconfig.json
            subPath: hawtconfig.json
        volumes:
        - name: hawtio-online
          configMap:
            name: hawtio-online
        - name: hawtio-integration
          configMap:
            name: hawtio-integration
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - hawtio-online
        from:
          kind: ImageStreamTag
          name: hawtio-online:latest
      type: ImageChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - hawtio-integration
        from:
          kind: ImageStreamTag
          name: hawtio-integration:latest
      type: ImageChange
    - type: ConfigChange
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: hawtio
      component: online
    name: hawtio-online
  spec:
    ports:
    - port: 80
      protocol: TCP
      targetPort: nginx
    selector:
      app: hawtio
      component: online
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: hawtio
      component: integration
    name: hawtio-integration
  spec:
    ports:
    - port: 80
      protocol: TCP
      targetPort: integration
    selector:
      app: hawtio
      component: online
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: hawtio
      component: online
    name: hawtio-online
  spec:
    host: ${ROUTE_HOSTNAME}
    to:
      kind: Service
      name: hawtio-online
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: hawtio
      component: integration
    name: hawtio-integration
  spec:
    host: ${ROUTE_HOSTNAME}
    path: /integration
    to:
      kind: Service
      name: hawtio-integration
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
- apiVersion: v1
  kind: OAuthClient
  metadata:
    name: hawtio-online
  redirectURIs:
  - https://${ROUTE_HOSTNAME}